- arguments: [-XNoPatternSynonyms, --cpp-define=HLINT]
- ignore: {name: Use const}
- ignore: {name: Use camelCase, within: Font.Config.Internal}
- ignore: {name: Use uncurry, within: Main}
- ignore: {name: Parse error}
- ignore: {name: Redundant do}
